### PR TITLE
Added tox testing to verify compatibility with different Python versions

### PR DESCRIPTION
**Pull request by fpgmaas**
I added `tox` testing to verify that `chunkdot` is compatible with different Python versions. For an example of the workflow, see [here](https://github.com/fpgmaas/chunkdot/actions/runs/4615551634).

It seems that `chunkdot` can currently not be installed on Python 3.11 because of a dependency issue.

Let me know what you think!

### CODE REVIEW

**Comment by rragundez** [comment]
Looks like a good addition. Let's check about the dependency issue first.

**Comment by fpgmaas** [comment]
The change with the `llvmlite` versions did not solve the issue, it seems; https://github.com/fpgmaas/chunkdot/pull/1/commits/c5dd3d8fbd1f7b8e0d2e1b0062ff3363c6888d89

Will need to investigate a bit more.

**Comment by fpgmaas** [comment]
@rragundez  It seems that numba is only supporting Python 3.11 after release 0.57, see [this issue](https://github.com/numba/numba/issues/8304). So for now I think it's best to have `chunkdot` support up to `3.10`, and update the dependency once `numba` `0.57` is released.

**Comment by rragundez** [comment]
LGTM. Thanks a lot!

**Pull request merged**
